version: "3.8"
name: davelopment-zone_devcontainer
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      # Mount ephemeral vault
      - ${EPHEMERAL_VAULT:-/no_ephemeral_vault}:/ephemeral_vault:ro
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db/postgres"
      KAFKA_BROKER_URL: "kafka:9092"
      # Pass the ephemeral key as an environment variable
      EPHEMERAL_RSA_KEY: "${EPHEMERAL_KEY:-no_ephemeral_key}"
    command: /bin/sh -c "bin/decrypt-ephemeral-secrets.sh && mix deps.get && mix phx.server"
    ports:
      - "4000:4000"
    depends_on:
      - db
      - kafka

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"

volumes:
  postgres-data:
