# .sops.yaml
creation_rules:
  - encrypted_regex: '(smtp_username|smtp_password|password|secret|key)$'
    pgp: 1D3FB3251AEEF90841E368D3D5C492AF4EE89913
    aws_profile: "sops-encryption-profile" # Optional, if using AWS KMS